const MIDI_STATUS = {
    NOTE_ON : "NOTE_ON",
    NOTE_OFF : "NOTE_OFF",
    POLYPHONIC_AFTER_TOUCHE: "POLYPHONIC_AFTER_TOUCHE",
    CONTROL_CHANGE: "CONTROL_CHANGE_CC",
    PROGRAM_CHANGE: "PROGRAM_CHANGE",
    CHANNEL_AFTER_TOUCHE : "CHANNEL_AFTER_TOUCHE",
    PITCH_WHEEL_RANGE: "PITCH_WHEEL_RANGE",
    SYSTEM_EXCLUSIVE: "SYSTEM_EXCLUSIVE",
    SYSTEM_COMMON : "SYSTEM_COMMON",
    SONG_POSITION_POINTER: "SONG_POSITION_POINTER",
    SONG_SELECT: "SONG_SELECT",
    TIMING_CLOCK: "TIMING_CLOCK",
    START: "START",
    CONTINUE: "CONTINUE",
    STOP: "STOP",
    ACTIVE_SENSING: "ACTIVE_SENSING",
    RESET: "SYSTEM_RESET",
    TUNE_REQUEST: "TUNE_REQUEST",
    END_SYSEX: "END_SYSEX",
    OTHER: "OTHER"
}
export default MIDI_STATUS;
